#!/bin/bash

if [ ! -n "${RT_SOURCE}" ] || [ ! -n "${RT_DESTINATION}" ]
then
  echo "Usage: ${0} /path/to/source.${RT_IN_FORMAT} /path/to/dest.${RT_OUT_FORMAT} width height"
  echo "Example: rgb ~/camera_images/img021.${RT_IN_FORMAT} ~/Photos/Me-and-Jeff.${RT_OUT_FORMAT} 720 480"
  exit 1
fi

RT_SIZE_ARG=""
if [ -n "${RT_WIDTH}" ] && [ -n "${RT_HEIGHT}" ]
then
  RT_SIZE_ARG="-s ${RT_SIZE}"
  #-s ${RT_SIZE} \
fi

ffmpeg \
  -f image2 \
  -vcodec ${RT_IN_FORMAT} \
  -i ${RT_SOURCE} \
  \
  -vcodec rawvideo \
  -f rawvideo \
  -pix_fmt ${RT_OUT_FORMAT} \
  ${RT_SIZE_ARG} ${RT_DESTINATION}

unset RT_DESTINATION
unset RT_SOURCE
unset RT_WIDTH
unset RT_HEIGHT
unset RT_SIZE
unset RT_IN_FORMAT
unset RT_OUT_FORMAT
