#!/bin/bash

PATH="./:${PATH}"

pngtorgb16 ../test/reference.png ./test.rgb16
pngtorgb24 ../test/reference.png ./test.rgb24

rgb16topng ./test.rgb16 ./test.png 720 480
rgb24tojpeg ./test.rgb24 ./test.jpeg 720 480
